### ISSUE TITLE
500 Internal Server Error - When signing up to an Event

### ISSUE THREAD

**Issue by meowserkat** [zeropingheroes/lanager#95] opened 2015-11-16 06:35 UTC
Logged: 2015-11-16 00:28:50 (5 minutes ago)
SAPI: APACHE2HANDLER
Level: Error
Message
Uncaught exception: ErrorException
Context
array(1) { [0]=> string(3492) "exception 'ErrorException' with message 'Undefined property: Zeropingheroes\Lanager\Domain\EventSignups\EventSignupService::$input' in /var/www/lanager/app/Domain/EventSignups/EventSignupService.php:64 Stack trace: #0 /var/www/lanager/app/Domain/EventSignups/EventSignupService.php(64): Illuminate\Exception\Handler->handleError(8, 'Undefined prope...', '/var/www/lanage...', 64, Array) #1 /var/www/lanager/app/Domain/ResourceService.php(307): Zeropingheroes\Lanager\Domain\EventSignups\EventSignupService->domainRulesOnStore(Array, Array) #2 /var/www/lanager/app/Domain/ResourceService.php(257): Zeropingheroes\Lanager\Domain\ResourceService->applyDomainRules('store', Array, Array) #3 /var/www/lanager/app/Domain/ResourceService.php(163): Zeropingheroes\Lanager\Domain\ResourceService->runChecks('store', Array) #4 /var/www/lanager/app/Domain/EventSignups/EventSignupService.php(17): Zeropingheroes\Lanager\Domain\ResourceService->store(Array) #5 /var/www/lanager/app/Http/Gui/ResourceServiceController.php(59): Zeropingheroes\Lanager\Domain\EventSignups\EventSignupService->store(Array) #6 /var/www/lanager/app/Http/Gui/EventSignupsController.php(42): Zeropingheroes\Lanager\Http\Gui\ResourceServiceController->processStore(Array) #7 [internal function]: Zeropingheroes\Lanager\Http\Gui\EventSignupsController->store('21') #8 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array) #9 /var/www/lanager/bootstrap/compiled.php(5847): Illuminate\Routing\Controller->callAction('store', Array) #10 /var/www/lanager/bootstrap/compiled.php(5835): Illuminate\Routing\ControllerDispatcher->call(Object(Zeropingheroes\Lanager\Http\Gui\EventSignupsController), Object(Illuminate\Routing\Route), 'store') #11 /var/www/lanager/bootstrap/compiled.php(5040): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Zeropingheroes\...', 'store') #12 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('21') #13 /var/www/lanager/bootstrap/compiled.php(5398): call_user_func_array(Object(Closure), Array) #14 /var/www/lanager/bootstrap/compiled.php(5065): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #15 /var/www/lanager/bootstrap/compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request)) #16 /var/www/lanager/vendor/dingo/api/src/Routing/Router.php(205): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #17 /var/www/lanager/bootstrap/compiled.php(715): Dingo\Api\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #18 /var/www/lanager/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #19 /var/www/lanager/bootstrap/compiled.php(7825): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true) #20 /var/www/lanager/bootstrap/compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true) #21 /var/www/lanager/bootstrap/compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true) #22 /var/www/lanager/bootstrap/compiled.php(11088): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true) #23 /var/www/lanager/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request)) #24 /var/www/lanager/public/index.php(49): Illuminate\Foundation\Application->run() #25 {main}" }

**Comment by ilumos** [comment] 2015-11-18 22:28
Thanks for the report, but as you saw this is a duplicate of #93

**Closed by ilumos** 2015-11-18 22:28 UTC
